version: "3"

services:
  app:
    image: app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: bdcalling
      DB_PASSWORD: bdcalling
      DB_NAME: bdcalling
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: bdcalling
      MONGO_INITDB_ROOT_PASSWORD: bdcalling

volumes:
  mongodata:
    driver: local
